name: harmonie
description: Application musicale intelligente — notes, accords, partitions
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^17.1.0

  # UI & Design
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # State management
  flutter_riverpod: ^3.3.1

  # Audio
  just_audio: ^0.10.5
  audio_session: ^0.2.3
  # Enregistrement
  record: ^5.0.4

  # Fichiers
  file_picker: ^10.3.10
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^12.0.1

  # Supabase
  supabase_flutter: ^2.3.4

  # Réseau
  dio: ^5.4.1
  http: ^1.2.0
  mime: ^2.0.0
  http_parser: ^4.0.0

  # Utilitaires
  intl: ^0.20.2
  uuid: ^4.3.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  record_linux: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/music.png
